version: '3.8'

services:
  trip-search-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      # 持久化日志
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "pm2", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PM2专用版本（可选）
  trip-search-mcp-pm2:
    build:
      context: .
      dockerfile: Dockerfile.pm2
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "pm2", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - pm2

  # 如果需要数据库或其他服务，可以在这里添加
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
